language: cpp
compiler:
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install libsdl1.2-dev libsdl-ttf2.0-dev libsdl-sound1.2-dev libsdl-sge-dev libsdl-pango-dev libsdl-net1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev cutter-testing-framework libjson0 libjson0-dev intltool libcap-dev libsndfile1 libsndfile1-dev
  - wget https://s3.amazonaws.com/json-c_releases/releases/json-c-0.12.tar.gz
  - tar -xzvf json-c-0.12.tar.gz
  - cd json-c-0.12
  - sed -i s/-Werror// Makefile.in && ./configure --prefix=/usr --disable-static && make -j1
  - sudo make install
  - cd ..
  - wget http://freedesktop.org/software/pulseaudio/releases/pulseaudio-4.0.tar.gz
  - tar -xzvf pulseaudio-4.0.tar.gz
  - ls -l
  - cd pulseaudio-4.0
  - ls -l
  - ./bootstrap.sh
  - ls -l
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
script: ./autogen.sh && ./configure && make
branches:
  only:
    - develop
notifications:
  recipients:
    - xincyberbit@gmail.com
  email:
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#cyberbitgame"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
  - linux
